package com.pennywiseai.tracker.domain.usecase

import android.util.Log
import com.pennywiseai.tracker.data.database.entity.SubscriptionDirection
import com.pennywiseai.tracker.data.database.entity.TransactionEntity
import com.pennywiseai.tracker.data.database.entity.TransactionType
import com.pennywiseai.tracker.data.repository.SubscriptionRepository
import com.pennywiseai.tracker.data.repository.TransactionRepository
import java.time.LocalDate
import java.time.LocalDateTime
import javax.inject.Inject

/**
 * Phantom-creates the transactions described by auto-generating recurring
 * subscriptions. Two kinds qualify (#371 + the 2026-07-07 auto-debit
 * extension): every INCOME-direction subscription (wallets, allowances,
 * internal top-ups that send no SMS when money arrives), and
 * EXPENSE-direction subscriptions the user explicitly opted into
 * auto-generation — recurring card auto-debits (insurance premium, telco)
 * that emit no SMS/notification either, statement-verified only. The user
 * declares "RM X on the Nth of every month" once; this use case
 * materialises the matching transaction the moment it's due (and catches
 * up if the user was away for several cycles).
 *
 * Runs on every SMS scan completion. Idempotent — the per-cycle
 * `transactionHash` is `"autopay-<subId>-<scheduledDate>"`, so a second
 * pass on the same day for the same subscription is dedup'd by
 * `TransactionRepository.getTransactionByHash`.
 */
class GenerateIncomeAutopayUseCase @Inject constructor(
    private val subscriptionRepository: SubscriptionRepository,
    private val transactionRepository: TransactionRepository
) {

    /** Returns the count of phantom transactions inserted. */
    suspend fun execute(today: LocalDate = LocalDate.now()): Int {
        val due = subscriptionRepository.getDueAutoGeneratedSubscriptions(today)
        if (due.isEmpty()) return 0

        var inserted = 0
        for (sub in due) {
            var scheduled = sub.nextPaymentDate ?: continue
            val isIncome = sub.direction == SubscriptionDirection.INCOME
            // Materialise every missed cycle up to today, not just one — a
            // user who didn't open the app for two months should see both
            // months' phantom rows, not just the most recent.
            while (!scheduled.isAfter(today)) {
                val hash = "autopay-${sub.id}-$scheduled"
                if (transactionRepository.getTransactionByHash(hash) == null) {
                    val phantom = TransactionEntity(
                        amount = sub.amount,
                        merchantName = sub.merchantName,
                        category = sub.category ?: if (isIncome) "Income" else "Others",
                        transactionType = if (isIncome) TransactionType.INCOME else TransactionType.EXPENSE,
                        dateTime = scheduled.atStartOfDay(),
                        description = if (isIncome) "Scheduled income (autopay)" else "Scheduled auto-debit (autopay)",
                        bankName = sub.bankName,
                        currency = sub.currency,
                        transactionHash = hash,
                        isRecurring = true,
                        createdAt = LocalDateTime.now(),
                        updatedAt = LocalDateTime.now()
                    )
                    val rowId = transactionRepository.insertTransaction(phantom)
                    if (rowId != -1L) inserted++
                }
                scheduled = subscriptionRepository.advance(scheduled, sub.billingCycle)
            }
            // Persist the final advanced date so the next scan starts from
            // there instead of replaying everything.
            subscriptionRepository.updateNextPaymentDate(sub.id, scheduled)
        }
        if (inserted > 0) Log.i(TAG, "Materialised $inserted scheduled income transactions.")
        return inserted
    }

    private companion object {
        const val TAG = "GenerateIncomeAutopay"
    }
}
